package Kriger.Calculator;

public class Convert {

    public static int rome_to_arabic(String value) throws CalcException {
        if (value.equals("I"))return 1;
        else if (value.equals("II")) return 2;
        else if (value.equals("III")) return 3;
        else if (value.equals("IV")) return 4;
        else if (value.equals("V")) return 5;
        else if (value.equals("VI")) return 6;
        else if (value.equals("VII")) return 7;
        else if (value.equals("VIII")) return 8;
        else if (value.equals("IX")) return 9;
        else if (value.equals("X")) return 10;
        else throw new CalcException("Римские цифры вне диапазона I - X");
    }

   public static String arabic_to_rome(int value) throws CalcException {
        if (value == 1) return "I";
        else if (value == 2) return "II";
        else if (value == 3) return "III";
        else if (value == 4) return "IV";
        else if (value == 5) return "V";
        else if (value == 6) return "VI";
        else if (value == 7) return "VII";
        else if (value == 8) return "VIII";
        else if (value == 9) return "IX";
        else if (value == 10) return "X";
        else if (value == 11) return "XI";
        else if (value == 12) return "XII";
        else if (value == 13) return "XIII";
        else if (value == 14) return "XIV";
        else if (value == 15) return "XV";
        else if (value == 16) return "XVI";
        else if (value == 17) return "XVII";
        else if (value == 18) return "XVIII";
        else if (value == 19) return "XIX";
        else if (value == 20) return "XX";
        else if (value == 21) return "XXI";
        else if (value == 22) return "XXII";
        else if (value == 23) return "XXIII";
        else if (value == 24) return "XXIV";
        else if (value == 25) return "XXV";
        else if (value == 26) return "XXVI";
        else if (value == 27) return "XXVII";
        else if (value == 28) return "XXVIII";
        else if (value == 29) return "XXIX";
        else if (value == 30) return "XXX";
        else if (value == 31) return "XXXI";
        else if (value == 32) return "XXXII";
        else if (value == 33) return "XXXIII";
        else if (value == 34) return "XXXIV";
        else if (value == 35) return "XXXV";
        else if (value == 36) return "XXXVI";
        else if (value == 37) return "XXXVII";
        else if (value == 38) return "XXXVIII";
        else if (value == 39) return "XXXIX";
        else if (value == 40) return "XL";
        else if (value == 41) return "XLI";
        else if (value == 42) return "XLII";
        else if (value == 43) return "XLIII";
        else if (value == 44) return "XLIV";
        else if (value == 45) return "XLV";
        else if (value == 46) return "XLVI";
        else if (value == 47) return "XLVII";
        else if (value == 48) return "XLVIII";
        else if (value == 49) return "XLIX";
        else if (value == 50) return "L";
        else if (value == 51) return "LI";
        else if (value == 52) return "LII";
        else if (value == 53) return "LIII";
        else if (value == 54) return "LIV";
        else if (value == 55) return "LV";
        else if (value == 56) return "LVI";
        else if (value == 57) return "LVII";
        else if (value == 58) return "LVIII";
        else if (value == 59) return "LIX";
        else if (value == 60) return "LX";
        else if (value == 61) return "LXI";
        else if (value == 62) return "LXII";
        else if (value == 63) return "LXIII";
        else if (value == 64) return "LXIV";
        else if (value == 65) return "LXV";
        else if (value == 66) return "LXVI";
        else if (value == 67) return "LXVII";
        else if (value == 68) return "LXVIII";
        else if (value == 69) return "LXIX";
        else if (value == 70) return "LXX";
        else if (value == 71) return "LXXI";
        else if (value == 72) return "LXXII";
        else if (value == 73) return "LXXIII";
        else if (value == 74) return "LXXIV";
        else if (value == 75) return "LXXV";
        else if (value == 76) return "LXXVI";
        else if (value == 77) return "LXXVII";
        else if (value == 78) return "LXXVIII";
        else if (value == 79) return "LXXIX";
        else if (value == 80) return "LXXX";
        else if (value == 81) return "LXXXI";
        else if (value == 82) return "LXXXII";
        else if (value == 83) return "LXXXIII";
        else if (value == 84) return "LXXXIV";
        else if (value == 85) return "LXXXV";
        else if (value == 86) return "LXXXVI";
        else if (value == 87) return "LXXXVII";
        else if (value == 88) return "LXXXVIII";
        else if (value == 89) return "LXXXIX";
        else if (value == 90) return "XC";
        else if (value == 91) return "XCI";
        else if (value == 92) return "XCII";
        else if (value == 93) return "XCIII";
        else if (value == 94) return "XCIV";
        else if (value == 95) return "XCV";
        else if (value == 96) return "XCVI";
        else if (value == 97) return "XCVII";
        else if (value == 98) return "XCVIII";
        else if (value == 99) return "XCIX";
        else if (value == 100) return "C";
        else throw new CalcException("Ответ вне диапазона римских чисел I...C");
    }
}
